spring:
  sql:
    init:
      mode: always
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/khan
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        globally_quoted_identifiers: true
        show_sql: true
        format_sql: true
        use_sql_comments: true
  thymeleaf:
    cache: false


  h2:
    console:
      enabled: true


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace


