INSERT INTO USERS (ID, PASSWORD, ROLE) VALUES ('username1', 'password1', 'USER');
INSERT INTO USERS (ID, PASSWORD, ROLE) VALUES ('username2', 'password2', 'ADMIN');
INSERT INTO USERS (ID, PASSWORD, ROLE) VALUES ('username3', 'password3', 'USER');
INSERT INTO USERS (ID, PASSWORD, ROLE) VALUES ('username4', 'password4', 'ADMIN');
INSERT INTO USERS (ID, PASSWORD, ROLE) VALUES ('username5', 'password5', 'USER');
INSERT INTO USERS (ID, PASSWORD, ROLE) VALUES ('username6', 'password6', 'ADMIN');

INSERT INTO STORES (STORE_NAME) VALUES ('Store1');
INSERT INTO STORES (STORE_NAME) VALUES ('Store2');
INSERT INTO STORES (STORE_NAME) VALUES ('Store3');
INSERT INTO STORES (STORE_NAME) VALUES ('Store4');
INSERT INTO STORES (STORE_NAME) VALUES ('Store5');
INSERT INTO STORES (STORE_NAME) VALUES ('Store6');

INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, PRODUCT_IMAGE, CREATE_DATE, LAST_MODIFIED_DATE)
VALUES ( '상품1' , 'white', 10.1, 23.2, '내용 없음', '/sd/sd.img', NOW(), NOW());
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, PRODUCT_IMAGE, CREATE_DATE, LAST_MODIFIED_DATE)
VALUES ( '상품2' , 'gold', 12.1, 21.2, '내용 없음', '/sd/ssdd.img', NOW(), NOW());
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, PRODUCT_IMAGE, CREATE_DATE, LAST_MODIFIED_DATE)
VALUES ( '상품3' , 'red', 14.1, 22.8, '내용 없음', '/sd/sasd.img', NOW(), NOW());
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, PRODUCT_IMAGE, CREATE_DATE, LAST_MODIFIED_DATE)
VALUES ( '상품4' , 'blue', 20.1, 23.9, '내용 없음', '/sd/ssssd.img', NOW(), NOW());
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, PRODUCT_IMAGE, CREATE_DATE, LAST_MODIFIED_DATE)
VALUES ( '상품5' , 'black', 30.1, 33.2, '내용 없음', '/sdssd/sd.img', NOW(), NOW());
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, PRODUCT_IMAGE, CREATE_DATE, LAST_MODIFIED_DATE)
VALUES ( '상품6' , 'white', 40.1, 53.2, '내용 없음', '/sd/sdsd.img', NOW(), NOW());

INSERT INTO FACTORIES (FACTORY_NAME) VALUES ( '공장1' );
INSERT INTO FACTORIES (FACTORY_NAME) VALUES ( '공장2' );
INSERT INTO FACTORIES (FACTORY_NAME) VALUES ( '공장3' );
INSERT INTO FACTORIES (FACTORY_NAME) VALUES ( '공장4' );
INSERT INTO FACTORIES (FACTORY_NAME) VALUES ( '공장5' );
INSERT INTO FACTORIES (FACTORY_NAME) VALUES ( '공장6' );

INSERT INTO PRODUCT_ORDER (PRODUCT_ORDER_QUANTITY, CREATE_DATE, LAST_MODIFIED_DATE, STORE_ID, USER_ID, CREATED_BY, LAST_MODIFIED_BY, PRODUCT_ORDER_TEXT )
VALUES ( 5, NOW(), NOW(), 1, 1, 'user1', 'user1', '내용 없음');
INSERT INTO PRODUCT_ORDER (PRODUCT_ORDER_QUANTITY, CREATE_DATE, LAST_MODIFIED_DATE, STORE_ID, USER_ID, CREATED_BY, LAST_MODIFIED_BY, PRODUCT_ORDER_TEXT)
VALUES ( 10, NOW(), NOW(),  2, 2, 'user2', 'user2', '내용 없음');
INSERT INTO PRODUCT_ORDER (PRODUCT_ORDER_QUANTITY, CREATE_DATE, LAST_MODIFIED_DATE, STORE_ID, USER_ID, CREATED_BY, LAST_MODIFIED_BY, PRODUCT_ORDER_TEXT)
VALUES ( 15, NOW(), NOW(), 3, 3, 'user3', 'user3', '내용 없음');
INSERT INTO PRODUCT_ORDER (PRODUCT_ORDER_QUANTITY, CREATE_DATE, LAST_MODIFIED_DATE, STORE_ID, USER_ID, CREATED_BY, LAST_MODIFIED_BY, PRODUCT_ORDER_TEXT)
VALUES ( 20, NOW(), NOW(), 4, 4, 'user4', 'user4', '내용 없음');

INSERT INTO PRODUCT_REGISTRATION (CREATE_DATE, FACTORY_ID, LAST_MODIFIED_DATE, PRODUCT_ID, USER_ID, CREATED_BY, LAST_MODIFIED_BY)
VALUES ( NOW(), 1, NOW(), 1,  1, 'user1', 'user1');
INSERT INTO PRODUCT_REGISTRATION (CREATE_DATE, FACTORY_ID, LAST_MODIFIED_DATE, PRODUCT_ID, USER_ID, CREATED_BY, LAST_MODIFIED_BY)
VALUES ( NOW(), 2, NOW(), 2,  2, 'user2', 'user2');
INSERT INTO PRODUCT_REGISTRATION (CREATE_DATE, FACTORY_ID, LAST_MODIFIED_DATE, PRODUCT_ID, USER_ID, CREATED_BY, LAST_MODIFIED_BY)
VALUES ( NOW(), 3, NOW(), 3,  3, 'user3', 'user3');
INSERT INTO PRODUCT_REGISTRATION (CREATE_DATE, FACTORY_ID, LAST_MODIFIED_DATE, PRODUCT_ID, USER_ID, CREATED_BY, LAST_MODIFIED_BY)
VALUES ( NOW(), 4, NOW(), 4,  4, 'user4', 'user4');