INSERT INTO USERS (PASSWORD, ROLE) VALUES ('password1', 'USER');
INSERT INTO USERS (PASSWORD, ROLE) VALUES ('password2', 'ADMIN');
INSERT INTO USERS (PASSWORD, ROLE) VALUES ('password3', 'USER');
INSERT INTO USERS (PASSWORD, ROLE) VALUES ('password4', 'ADMIN');
INSERT INTO USERS (PASSWORD, ROLE) VALUES ('password5', 'USER');
INSERT INTO USERS (PASSWORD, ROLE) VALUES ('password6', 'ADMIN');

INSERT INTO STORES (STORE_NAME) VALUES ('Store1');
INSERT INTO STORES (STORE_NAME) VALUES ('Store2');
INSERT INTO STORES (STORE_NAME) VALUES ('Store3');
INSERT INTO STORES (STORE_NAME) VALUES ('Store4');
INSERT INTO STORES (STORE_NAME) VALUES ('Store5');
INSERT INTO STORES (STORE_NAME) VALUES ('Store6');

INSERT INTO FACTORIES (FACTORY_NAME) VALUES ( '공장1' );
INSERT INTO FACTORIES (FACTORY_NAME) VALUES ( '공장2' );
INSERT INTO FACTORIES (FACTORY_NAME) VALUES ( '공장3' );
INSERT INTO FACTORIES (FACTORY_NAME) VALUES ( '공장4' );
INSERT INTO FACTORIES (FACTORY_NAME) VALUES ( '공장5' );
INSERT INTO FACTORIES (FACTORY_NAME) VALUES ( '공장6' );

INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품1', 'white', 10.1, 23.2, '내용 없음', NOW(), NOW(), 1, 1);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품2', 'gold', 12.1, 21.2, '내용 없음', NOW(), NOW(), 2, 2);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품3', 'red', 14.1, 22.8, '내용 없음', NOW(), NOW(), 3, 3);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품4', 'blue', 20.1, 23.9, '내용 없음', NOW(), NOW(), 4, 4);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품5', 'black', 30.1, 33.2, '내용 없음', NOW(), NOW(), 5, 5);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품6', 'white', 40.1, 53.2, '내용 없음', NOW(), NOW(), 6, 6);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품7', 'white', 10.1, 23.2, '내용 없음', NOW(), NOW(), 1, 2);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품8', 'gold', 12.1, 21.2, '내용 없음', NOW(), NOW(), 2, 3);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품9', 'red', 14.1, 22.8, '내용 없음', NOW(), NOW(), 3, 4);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품10', 'blue', 20.1, 23.9, '내용 없음', NOW(), NOW(), 4, 5);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품11', 'black', 30.1, 33.2, '내용 없음', NOW(), NOW(), 5, 6);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품12', 'white', 40.1, 53.2, '내용 없음', NOW(), NOW(), 6, 1);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품13', 'white', 10.1, 23.2, '내용 없음', NOW(), NOW(), 1, 2);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품14', 'gold', 12.1, 21.2, '내용 없음', NOW(), NOW(), 2, 3);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품15', 'red', 14.1, 22.8, '내용 없음', NOW(), NOW(), 3, 4);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품16', 'blue', 20.1, 23.9, '내용 없음', NOW(), NOW(), 4, 5);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품17', 'black', 30.1, 33.2, '내용 없음', NOW(), NOW(), 5, 6);
INSERT INTO PRODUCTS (PRODUCT_NAME, PRODUCT_COLOR, PRODUCT_SIZE, PRODUCT_WEIGHT, PRODUCT_OTHER, CREATE_DATE, LAST_MODIFIED_DATE, USER_ID, FACTORY_ID)
VALUES ('상품18', 'white', 40.1, 53.2, '내용 없음', NOW(), NOW(), 6, 1);

INSERT INTO PRODUCT_IMAGE (IMAGE_PATH, PRODUCT_ID) VALUES ('/path/to/image1.jpg', 1);
INSERT INTO PRODUCT_IMAGE (IMAGE_PATH, PRODUCT_ID) VALUES ('/path/to/image2.jpg', 1);

-- INSERT INTO PRODUCT_ORDER (CREATE_DATE, LAST_MODIFIED_DATE, STORE_ID, USER_ID, CREATED_BY, LAST_MODIFIED_BY)
-- VALUES (NOW(), NOW(), 1, 1, 'user1', 'user1');
-- INSERT INTO PRODUCT_ORDER (CREATE_DATE, LAST_MODIFIED_DATE, STORE_ID, USER_ID, CREATED_BY, LAST_MODIFIED_BY)
-- VALUES ( NOW(), NOW(),  2, 2, 'user2', 'user2');
-- INSERT INTO PRODUCT_ORDER (CREATE_DATE, LAST_MODIFIED_DATE, STORE_ID, USER_ID, CREATED_BY, LAST_MODIFIED_BY)
-- VALUES (NOW(), NOW(), 3, 3, 'user3', 'user3', '내용 없음');
-- INSERT INTO PRODUCT_ORDER ( CREATE_DATE, LAST_MODIFIED_DATE, STORE_ID, USER_ID, CREATED_BY, LAST_MODIFIED_BY)
-- VALUES (NOW(), NOW(), 4, 4, 'user4', 'user4', '내용 없음');
-- INSERT INTO PRODUCT_ORDER (CREATE_DATE, LAST_MODIFIED_DATE, STORE_ID, USER_ID, CREATED_BY, LAST_MODIFIED_BY)
-- VALUES (NOW(), NOW(), 4, 4, 'user5', 'user5', '내용 없음');
-- INSERT INTO PRODUCT_ORDER (CREATE_DATE, LAST_MODIFIED_DATE, STORE_ID, USER_ID, CREATED_BY, LAST_MODIFIED_BY)
-- VALUES (NOW(), NOW(), 4, 4, 'user6', 'user6', '내용 없음');

-- INSERT INTO PRODUCT_ORDER_ITEM
-- (PRODUCT_ORDER_ITEM_NAME, PRODUCT_ORDER_ITEM_COLOR, PRODUCT_ORDER_ITEM_SIZE, PRODUCT_ORDER_ITEM_WEIGHT, PRODUCT_ORDER_ITEM_OTHER, PRODUCT_ORDER_ID, PRODUCT_ID, PRODUCT_ORDER_ITEM_QUANTITY)
-- VALUES
--     ('주문 아이템 1', 'white', 10.1, 5.0, '기타 정보', 1, 1, 1),
--     ('주문 아이템 2', 'gold', 12.1, 6.0, '기타 정보', 2, 2, 1),
--     ('주문 아이템 3', 'red', 14.1, 7.0, '기타 정보', 3, 3, 1),
--     ('주문 아이템 4', 'blue', 20.1, 8.0, '기타 정보', 4, 4, 1),
--     ('주문 아이템 5', 'black', 30.1, 9.0, '기타 정보', 1, 5, 1),
--     ('주문 아이템 6', 'white', 40.1, 10.0, '기타 정보', 2, 6, 1);
